export const ActivitiesData = [
  {
    id: 1,
    value: 1,
    text: "Sportas",
    url: "/sportas.svg",
  },
  {
    id: 2,
    value: 2,
    text: "Informacinės technologijos",
    url: "/technologijos.svg",
  },
  {
    id: 3,
    value: 3,
    text: "Teatras, drama",
    url: "/drama.svg",
  },
  {
    id: 4,
    value: 4,
    text: "Kalbos",
    url: "/kalbos.svg",
  },
  {
    id: 5,
    value: 5,
    text: "Choreografija, šokis",
    url: "/choreografija.svg",
  },
  {
    id: 6,
    value: 6,
    text: "Dailė",
    url: "/daile.svg",
  },
  {
    id: 7,
    value: 7,
    text: "Muzika",
    url: "/muzika.svg",
  },
  {
    id: 8,
    value: 8,
    text: "Turizmas ir kraštotyra",
    url: "/turizmas.svg",
  },
  {
    id: 9,
    value: 9,
    text: "Etnokultūra",
    url: "/etnokultura.svg",
  },
  {
    id: 10,
    value: 10,
    text: "Gamta, ekologija",
    url: "/gamta.svg",
  },
  {
    id: 11,
    value: 11,
    text: "Techninė kūryba",
    url: "/technine_kuryba.png",
  },
  {
    id: 12,
    value: 12,
    text: "Pilietiškumas",
    url: "/pilietiskumas.svg",
  },
  {
    id: 13,
    value: 13,
    text: "Medijos",
    url: "/medijos.svg",
  },
  {
    id: 14,
    value: 14,
    text: "Technologijos",
    url: "/technologijos.svg",
  },
  {
    id: 15,
    value: 15,
    text: "Kitos veiklos",
    url: "/medijos.svg",
  },
  {
    id: 16,
    value: 16,
    text: "Saugus eismas",
    url: "/saugus_eismas.svg",
  },
];
